In [1]:
import pandas as pd
import csv
import datetime as dt

In [2]:
cd /scratch/group/history/hist_3368-jguldi

/scratch/group/history/hist_3368-jguldi

In [3]:
congress = pd.read_csv("congress1967-2010.csv")

In [4]:
congress.head()

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
0,0,0,Those who do not enjoy the privilege of the fl...,1967-01-10,The VICE PRESIDENT,16,1967,1,1967-01-01
1,1,1,Mr. President. on the basis of an agreement re...,1967-01-10,Mr. MANSFIELD,35,1967,1,1967-01-01
2,2,2,The Members of the Senate have heard the remar...,1967-01-10,The VICE PRESIDENT,40,1967,1,1967-01-01
3,3,3,The Chair lays before the Senate the following...,1967-01-10,The VICE PRESIDENT,151,1967,1,1967-01-01
4,4,4,Secretary of State.,1967-01-10,Mrs. AGNES BAGGETT,3,1967,1,1967-01-01

In [5]:
congress = congress[congress['year']< 1970]

In [6]:
congress['speaker']

0               The VICE PRESIDENT
1                    Mr. MANSFIELD
2               The VICE PRESIDENT
3               The VICE PRESIDENT
4               Mrs. AGNES BAGGETT
                    ...
484624                Mr. RUMSFELO
484625                Mr. RuMSFELD
484626    Mr. ANDERSON of Illinois
484627                Mr. ZABLOCKI
484628                Mr. PUCINSKI
Name: speaker, Length: 484629, dtype: object

In [7]:
congress[['speaker']]

                         speaker
0             The VICE PRESIDENT
1                  Mr. MANSFIELD
2             The VICE PRESIDENT
3             The VICE PRESIDENT
4             Mrs. AGNES BAGGETT
...                          ...
484624              Mr. RUMSFELO
484625              Mr. RuMSFELD
484626  Mr. ANDERSON of Illinois
484627              Mr. ZABLOCKI
484628              Mr. PUCINSKI

[484629 rows x 1 columns]

In [8]:
congress['speech'][0]

'Those who do not enjoy the privilege of the floor will please retire from the Chamber.'

In [9]:
congress.iloc[1005:1008,]

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
1005,1005,1005,Mr. President. for many years I have advocated...,1967-01-11,Mr. WILLIAMS of Delaware,184,1967,1,1967-01-01
1006,1006,1006,I am delighted to have the Senator from Delawa...,1967-01-11,Mr. DIRKSEN,27,1967,1,1967-01-01
1007,1007,1007,Mr. President. I submit a resolution to amend ...,1967-01-11,Mr. CANNON,449,1967,1,1967-01-01

In [10]:
congress.loc[:, ['speaker', 'speech']].iloc[3234, :]

speaker                                            Mr. TOWER
speech     Mr. President. on June 17. a starting gun will...
Name: 3234, dtype: object

In [11]:
congress[congress['speaker'] == 'Mr. DOLE']

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
7475,7475,7475,"Mr. Speaker. the January 8. 1967. ""Doanes Agri...",1967-02-01,Mr. DOLE,201,1967,2,1967-02-01
8657,8657,8657,Mr. Speaker. I ask unanimous consent to revise...,1967-02-02,Mr. DOLE,12,1967,2,1967-02-01
8659,8659,8659,Mr. Speaker. I join in the statements made by ...,1967-02-02,Mr. DOLE,301,1967,2,1967-02-01
8767,8767,8767,Mr. Speaker. it is my pleasure to join in the ...,1967-02-02,Mr. DOLE,878,1967,2,1967-02-01
12255,12255,12255,Mr. Speaker. today I have introduced a joint r...,1967-02-09,Mr. DOLE,82,1967,2,1967-02-01
...,...,...,...,...,...,...,...,...,...
483800,483800,483800,Mr. President. scattered across the Nation are...,1969-12-23,Mr. DOLE,140,1969,12,1969-12-01
483962,483962,483962,Mr. President. will the Senator yield?,1969-12-23,Mr. DOLE,6,1969,12,1969-12-01
483964,483964,483964,The charge has been made that President Nixon ...,1969-12-23,Mr. DOLE,79,1969,12,1969-12-01
483966,483966,483966,The Senator indicates-,1969-12-23,Mr. DOLE,3,1969,12,1969-12-01
483968,483968,483968,We agree that reasonable men can reach a reaso...,1969-12-23,Mr. DOLE,21,1969,12,1969-12-01

In [12]:
pineapplespeakers = ['Mr. FONG', 'Mrs. MINK', 'Mr. MATSUNAGA']
congress[congress['speaker'].isin(pineapplespeakers)]

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
1541,1541,1541,Mr. Speaker. it was my great privilege to list...,1967-01-16,Mr. MATSUNAGA,281,1967,1,1967-01-01
1907,1907,1907,Mr. President. the Senate is now considering t...,1967-01-17,Mr. FONG,873,1967,1,1967-01-01
2136,2136,2136,"Mr. Speaker. the editorial entitled ""Speaker o...",1967-01-17,Mr. MATSUNAGA,347,1967,1,1967-01-01
2276,2276,2276,Mr. Speaker. I rise to pay tribute to the memo...,1967-01-18,Mr. MATSUNAGA,18,1967,1,1967-01-01
2296,2296,2296,Mr. Speaker. I. along with all my colleagues. ...,1967-01-18,Mrs. MINK,200,1967,1,1967-01-01
...,...,...,...,...,...,...,...,...,...
481483,481483,481483,This everyone understands. This is our security.,1969-12-20,Mr. FONG,7,1969,12,1969-12-01
481485,481485,481485,The Senator is correct.,1969-12-20,Mr. FONG,4,1969,12,1969-12-01
482214,482214,482214,Mr. Speaker. the Island of Hawaii. youngest an...,1969-12-20,Mr. MATSUNAGA,344,1969,12,1969-12-01
483072,483072,483072,Mr. Speaker. will the gentleman yield?,1969-12-22,Mr. MATSUNAGA,6,1969,12,1969-12-01
483074,483074,483074,Will the gentleman from Arkansas explain what ...,1969-12-22,Mr. MATSUNAGA,14,1969,12,1969-12-01

In [13]:
congress[congress['month'].isin(range(6,8))]

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
63624,63624,63624,Mr. President. on April 19 the United Auto Wor...,1967-06-01,Mr. HARTKE,227,1967,6,1967-06-01
63625,63625,63625,Without objection. it is so ordered. The resol...,1967-06-01,The PRESIDING OFFICER,17,1967,6,1967-06-01
63626,63626,63626,Mr. President. I ask unanimous consent that th...,1967-06-01,Mr. McCLELLAN,47,1967,6,1967-06-01
63627,63627,63627,Without objection. it is so ordered.,1967-06-01,The PRESIDING OFFICER,6,1967,6,1967-06-01
63628,63628,63628,Mr. President. I ask unanimous consent that th...,1967-06-01,Mr. DIRKSEN,23,1967,6,1967-06-01
...,...,...,...,...,...,...,...,...,...
399440,399440,399440,Mr. Speaker. this morning. I testified before ...,1969-07-31,Mr. DON H. CLAUSEN,562,1969,7,1969-07-01
399441,399441,399441,Mr. Speaker. the Ways and Means Committee last...,1969-07-31,Mr. YOUNG,80,1969,7,1969-07-01
399442,399442,399442,Mr. Speaker. under leave to extend my remarks ...,1969-07-31,Mr. FULTON of Pennsylvania,20,1969,7,1969-07-01
399443,399443,399443,Mr. Speaker. earlier this month.-at the very t...,1969-07-31,Mr. SCHEUER,337,1969,7,1969-07-01
399444,399444,399444,Mr. Speaker. on the eve of the Apollo 11 fligh...,1969-07-31,Mr. MARSH,80,1969,7,1969-07-01

In [14]:
congress.nlargest(10, 'word_count')

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year
321802,321802,321802,Mr. President. the question is: Will the Senat...,1968-09-30,Mr. EASTLAND,19786,1968,9,1968-09-01
329781,329781,329781,Yes. about three doors up. Senator BYRD. So th...,1968-10-10,Mrs..H,18112,1968,10,1968-10-01
1729,1729,1729,Mr. President. I rise in objection to this mot...,1967-01-16,Mr. ERVIN,17772,1967,1,1967-01-01
317366,317366,317366,and Foreign Commissar Maxim Litvinov was sent ...,1968-09-23,US.S.R,14715,1968,9,1968-09-01
410918,410918,410918,Oh. we want depletion done away with entirely ...,1969-09-09,The CHAIRMAN,14354,1969,9,1969-09-01
467198,467198,467198,Maritime Administration. Washington. D.C. Gibs...,1969-12-10,tor. U.S,13139,1969,12,1969-12-01
391705,391705,391705,Mr. President. the destructiveness of nuclear ...,1969-07-22,Mr. GORE,12046,1969,7,1969-07-01
321780,321780,321780,Mr. President. in discussing a matter such as ...,1968-09-30,Mr. STENNIS,11723,1968,9,1968-09-01
174559,174559,174559,Mr. Speaker. the May 1967. National Review car...,1967-11-30,Mr. RARICK,11197,1967,11,1967-11-01
108062,108062,108062,Mr. Speaker. today I have introduced the Fresh...,1967-08-16,Mr. KUPFERMAN,11145,1967,8,1967-08-01

In [15]:
len(congress['speaker'])

484629

In [16]:
len(congress['speaker'].unique())

7165

In [17]:
congress['speech'].str.split().str.len()

0          16
1          35
2          40
3         151
4           3
         ...
484624    114
484625      4
484626     64
484627    300
484628    319
Name: speech, Length: 484629, dtype: int64

In [18]:
len(congress['speech'][0].split())

16

In [19]:
congress['speaker'].count()

484629

In [20]:
congress['speaker'].str.count('Mr. MANSFIELD')

0         0
1         1
2         0
3         0
4         0
         ..
484624    0
484625    0
484626    0
484627    0
484628    0
Name: speaker, Length: 484629, dtype: int64

In [21]:
congress['speech'][1].count('President')

1

In [22]:
congress['speech'].str.count('President')

0         0
1         1
2         0
3         0
4         0
         ..
484624    2
484625    0
484626    0
484627    3
484628    0
Name: speech, Length: 484629, dtype: int64

In [23]:
congress['speaker'].value_counts()

The PRESIDING OFFICER              32220
The SPEAKER                        19920
Mr. MANSFIELD                      13506
The CHAIRMAN                       11373
The SPEAKER pro tempore            11145
                                   ...
Mr. WILLIAM RANDOLPH HEARST. Jr        1
Dr. DAVID M. SNYDER                    1
Dr. GLENN                              1
Miss JUDI COVINGTON                    1
er. CHARLES E. GOODELL                 1
Name: speaker, Length: 7165, dtype: int64

In [24]:
pd.Series.value_counts(list(congress['speech'][0].split()))

the          3
do           1
will         1
floor        1
please       1
who          1
Chamber.     1
retire       1
from         1
privilege    1
of           1
Those        1
not          1
enjoy        1
dtype: int64

In [26]:
import string
congress['speech'] = congress['speech'].str.replace('[{}]'.format(string.punctuation), '')

In [27]:
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stop = stopwords.words('english')
stopwords_regex = r'\b(?:{})\b'.format('|'.join(stop))
stopwords_regex
congress['stopworded'] = congress['speech'].str.replace(stopwords_regex, '')
congress.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     /users/jguldi/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,Unnamed: 0,Unnamed: 0.1,speech,date,speaker,word_count,year,month,month_year,stopworded
0,0,0,Those who do not enjoy the privilege of the fl...,1967-01-10,The VICE PRESIDENT,16,1967,1,1967-01-01,Those enjoy privilege floor please reti...
1,1,1,Mr President on the basis of an agreement reac...,1967-01-10,Mr. MANSFIELD,35,1967,1,1967-01-01,Mr President basis agreement reached sid...
2,2,2,The Members of the Senate have heard the remar...,1967-01-10,The VICE PRESIDENT,40,1967,1,1967-01-01,The Members Senate heard remarks disting...
3,3,3,The Chair lays before the Senate the following...,1967-01-10,The VICE PRESIDENT,151,1967,1,1967-01-01,The Chair lays Senate following matters Cop...
4,4,4,Secretary of State,1967-01-10,Mrs. AGNES BAGGETT,3,1967,1,1967-01-01,Secretary State

In [29]:
congress['speech'][1]

'Mr President on the basis of an agreement reached on both sides it is suggested that the Chamber be cleared of all attaches unless they have absolutely important business to attend to in the Chamber'

In [28]:

congress['stopworded'][1]

'Mr President   basis   agreement reached   sides   suggested   Chamber  cleared   attaches unless   absolutely important business  attend    Chamber'

In [31]:
congress['speech'][0].split()

['Those',
 'who',
 'do',
 'not',
 'enjoy',
 'the',
 'privilege',
 'of',
 'the',
 'floor',
 'will',
 'please',
 'retire',
 'from',
 'the',
 'Chamber']

In [32]:
congress['speech'].str.split()

0         [Those, who, do, not, enjoy, the, privilege, o...
1         [Mr, President, on, the, basis, of, an, agreem...
2         [The, Members, of, the, Senate, have, heard, t...
3         [The, Chair, lays, before, the, Senate, the, f...
4                                    [Secretary, of, State]
                                ...
484624    [Well, thats, one, quote, I, hadnt, heard, And...
484625                             [Thank, you, very, much]
484626    [Mr, Speaker, the, first, session, of, the, 91...
484627    [Mr, Speaker, as, we, look, back, on, the, rec...
484628    [Mr, Speaker, Marshall, Field, publisher, of, ...
Name: speech, Length: 484629, dtype: object

In [ ]:
import datetime as dt

In [ ]:
congress['date'][0].dt.year

In [ ]:
congress['date'].dt.year